"$schema" = 'https://starship.rs/config-schema.json'
palette = 'catppuccin_mocha'

format = """
[](red)\
$os\
$username\
[](fg:red bg:peach)\
$directory\
[](fg:peach bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:blue)\
$docker_context\
[](fg:blue bg:mauve)\
$time\
[ ](fg:mauve)\
$line_break$character"""

[os]
disabled = false
style = "bg:red fg:mantle"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:red fg:mantle"
style_root = "bg:red fg:mantle"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol $branch ](fg:mantle bg:yellow)]($style)'

[git_status]
style = "bg:mantle"
format = '[[($all_status$ahead_behind )](fg:mantle bg:yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:mantle bg:green)]($style)'

[c]
symbol = " "
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:mantle bg:green)]($style)'

[rust]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:mantle bg:green)]($style)'

[golang]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:mantle bg:green)]($style)'

[php]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:mantle bg:green)]($style)'

[java]
symbol = " "
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:mantle bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:mantle bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:mantle bg:green)]($style)'

[python]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $version) ](fg:mantle bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:mantle bg:blue)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:mantle"
format = '[[  $time ](fg:mantle bg:mauve)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
