general:
  startup_commands: [shell-exec zebar]
  shutdown_commands: [shell-exec taskkill /IM zebar.exe /F]
  config_reload_commands: []
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: true
    trigger: 'window_focus'
  hide_method: 'hide'

gaps:
  scale_with_dpi: false
  inner_gap: '4px'
  outer_gap:
    top: '0px'
    right: '4px'
    bottom: '4px'
    left: '4px'

window_effects:
  focused_window:
    border:
      enabled: true
      color: "#89b4fa"
    hide_title_bar:
      enabled: true
    corner_style:
      enabled: true
      style: small_rounded
  other_windows:
    border:
      enabled: true
      color: "#b4befe"
    hide_title_bar:
      enabled: true
    corner_style:
      enabled: true
      style: small_rounded

window_behavior:
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: false
      shown_on_top: false

workspaces:
  - name: '1'
    keep_alive: true
    bind_to_monitor: 0
  - name: '2'
    keep_alive: true
    bind_to_monitor: 0
  - name: '3'
    keep_alive: true
    bind_to_monitor: 1
  - name: '4'
    keep_alive: true
    bind_to_monitor: 1
  - name: '5'
    keep_alive: true
    bind_to_monitor: 0
  - name: '6'
    keep_alive: true
    bind_to_monitor: 0
  - name: '7'
    keep_alive: true
    bind_to_monitor: 1
  - name: '8'
    keep_alive: true
    bind_to_monitor: 1

window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }
      - window_process: { equals: 'Flow.Launcher' }
      - window_process: { equals: 'r5apex' } # Apex Legends
      - window_process: { equals: 'Marvel-Win64-Shipping' } # Marvel Rivals
      - window_process: { equals: 'VALORANT-Win64-Shipping' } # Valorant
      - window_process: { equals: 'Discovery' } # The Finals
      - window_process: { equals: 'Overwatch' } # Overwatch 2
      - window_process: { equals: 'League of Legends' } # League of Legends
      - window_process: { equals: 'start_protected_game' } # Elden Ring
      - window_process: { equals: 'DarkSoulsIII' } # Dark Souls 3

binding_modes: []

keybindings:
  - commands: ['shell-exec C:\Program Files\Zen Browser\zen.exe'] # Zen Browser
    bindings: ['f22+b']
  - commands: ['shell-exec C:\Users\conaN\AppData\Local\Discord\Update.exe --processStart Discord.exe'] # Discord
    bindings: ['f22+d']
  - commands: ['shell-exec explorer'] # File Explorer
    bindings: ['f22+e']
  - commands: ['shell-exec code'] # Visual Studio Code
    bindings: ['f22+c']
  - commands: ['shell-exec C:\Users\conaN\AppData\Local\Programs\Obsidian\Obsidian.exe'] # Obsidian
    bindings: ['f22+o']
  - commands: ['shell-exec C:\Program Files (x86)\Steam\steam.exe'] # Steam
    bindings: ['f22+s']

  - commands: ['focus --direction left']
    bindings: ['f22+h']
  - commands: ['focus --direction right']
    bindings: ['f22+l']
  - commands: ['focus --direction up']
    bindings: ['f22+k']
  - commands: ['focus --direction down']
    bindings: ['f22+j']

  - commands: ['move --direction left']
    bindings: ['f22+shift+h']
  - commands: ['move --direction right']
    bindings: ['f22+shift+l']
  - commands: ['move --direction up']
    bindings: ['f22+shift+k']
  - commands: ['move --direction down']
    bindings: ['f22+shift+j']

  - commands: ['resize --width -5%']
    bindings: ['f22+alt+h']
  - commands: ['resize --width +5%']
    bindings: ['f22+alt+l']
  - commands: ['resize --height +5%']
    bindings: ['f22+alt+k']
  - commands: ['resize --height -5%']
    bindings: ['f22+alt+j']

  - commands: ['toggle-tiling-direction']
    bindings: ['f22+space']

  - commands: ['toggle-minimized']
    bindings: ['f22+m']

  - commands: ['close']
    bindings: ['f22+q']

  - commands: ['toggle-floating --centered']
    bindings: ['f22+shift+f']

  - commands: ['toggle-tiling']
    bindings: ['f22+f']

  - commands: ['focus --workspace 1']
    bindings: ['f22+1']
  - commands: ['focus --workspace 2']
    bindings: ['f22+2']
  - commands: ['focus --workspace 3']
    bindings: ['f22+3']
  - commands: ['focus --workspace 4']
    bindings: ['f22+4']
  - commands: ['focus --workspace 5']
    bindings: ['f22+5']
  - commands: ['focus --workspace 6']
    bindings: ['f22+6']
  - commands: ['focus --workspace 7']
    bindings: ['f22+7']
  - commands: ['focus --workspace 8']
    bindings: ['f22+8']

  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['f22+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['f22+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['f22+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['f22+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['f22+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['f22+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['f22+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['f22+shift+8']
